### ISSUE TITLE
ZipUtils' rollback may delete unwanted data

### ISSUE THREAD

**Issue by AnderWeb** [commonsguy/cwac-security#11]
The current implementation of ZipUtils deletes the whole destDir when an exception occurs.

I can see developers unzipping stuff into a directory already containing files and loosing everything cause of this. 

I'm not sure what would be the best approach:

1-Make a list of extracted files and delete only them instead of the whole directory (this may still cause issues with already existent, overwritten files).

2-Unzip into a temp directory and, if no errors detected, move everything into destDir (maybe with an optional boolean flag to allow/deny overwriting already existing files).

3-Leave as is but provide a better documentation (or warning somewhat) the "I will delete everything on fail".

**Comment by commonsguy** [comment]
Excellent point, though I went with a different option: the destination directory either must not exist or must be empty. `unzip()` fails fast on a non-empty destination. Developers using `unzip()` who want to unzip into a directory with content can implement #2 themselves, by passing `unzip()` a temporary directory and moving the contents into the desired target. Trying to handle overwrites myself feels like a rabbit hole that I don't want to go down.

Addressed in v0.5.2.

Thanks!
