### ISSUE TITLE
can not resolve method open

### ISSUE THREAD

**Issue by albertsmus** [commonsguy/cwac-security#12]
from this: https://github.com/commonsguy/cwac-security/blob/master/TrustManagerBuilder.markdown
i used:
TrustManagerBuilder builder=new TrustManagerBuilder();

// configure builder here

SSLContext ssl=SSLContext.getInstance("TLS")

ssl.init(null, builder.buildArray(), null);

OkHttpClient okHttpClient=new OkHttpClient();

okHttpClient.setSslSocketFactory(ssl.getSocketFactory());

HttpURLConnection conn=okHttpClient.open(new URL(url));

But on HttpURLConnection conn=okHttpClient.open(new URL(url)); i get this error: "can not resolve method open"

**Comment by commonsguy** [comment]
Those directions are for OkHttp 1.x; the 2.x API may be different. Moreover, this has nothing to do with CWAC-Security (other than the example code being a bit stale). The [OkHttp site](https://github.com/square/okhttp) is where you will need to research the current ways of using the `HttpUrlConnection` compatibility layer. Personally, I use OkHttp's native API.

**Comment by albertsmus** [comment]
May i  ask a question about:
https://github.com/commonsguy/cw-omnibus/blob/master/Service/Downloader/src/com/commonsware/android/downloader/Downloader.java
?


2015-11-16 19:03 GMT+02:00 Mark Murphy <notifications@github.com>:

**Comment by commonsguy** [comment]
Well, not here. This is an issue tracker for a specific project, not a place to ask random Android questions.

If you are a [subscriber](https://commonsware.com/warescription), join an office hours chat, and we can talk about all sorts of Android development topics.

If you can phrase your question more generally, perhaps using that code as an example of your area of concern, there are many [Android developer support sites](http://www.andglobe.com) that you can use.
