### ISSUE TITLE
Error during gradle sync

### ISSUE THREAD

**Issue by simonojok19** [commonsguy/cwac-security#22]
implementation 'com.commonsware.cwac:security:0.8.0'
 url "https://s3.amazonaws.com/repo.commonsware.com"
Error occured during sync
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.commonsware.cwac:security:0.8.0.

**Comment by commonsguy** [comment]
You need to add the Maven repo:

```
repositories {
    maven {
        url "https://s3.amazonaws.com/repo.commonsware.com"
    }
}
```

**Comment by simonojok19** [comment]
Sir. All links you include in the Bust coder guide to android development
are not work. May be aws is down

https://s3.amazonaws.com/repo.commonsware.com is not working in Uganda
Africa. Please maybe you check on the permissions you have on the
documents

[image: commonsware.JPG]


[image: Makerere University]

Simon Peter Ojok
Student | Makerere University | SCIT
phone: +256754140200
mobile: +256772241709
email: simonojok19@gmail.com
address: Kampala-Uganda
<http://pysimonojok/>
<http://pysimonojok/>
<http://pysimonojok/>
<http://7.176.192.128/>



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by commonsguy** [comment]
Try visiting https://s3.amazonaws.com/repo.commonsware.com/ in your Web browser. Then, try visiting http://repo.commonsware.com/ in your Web browser.

- If they both return an XML document, then AWS S3 access is fine in Uganda

- If the second link returns an XML document, and the first does not, then SSL access to AWS is unavailable in Uganda, and you would need to set your repo to point to http://repo.commonsware.com/

- If neither link works, then AWS S3 is unavailable in Uganda

**Comment by simonojok19** [comment]
Thanks this is working


[image: Makerere University]

Simon Peter Ojok
Student | Makerere University | SCIT
phone: +256754140200
mobile: +256772241709
email: simonojok19@gmail.com
address: Kampala-Uganda
<http://pysimonojok/>
<http://pysimonojok/>
<http://pysimonojok/>
<http://7.176.192.128/>

**Comment by commonsguy** [comment]
Great! Thanks for letting me know!

**Comment by simonojok19** [comment]
Please i don't know but i have found out that most of people learning
android development and following ur book are have similar problems you
have just fixed with me.
I suggest that maybe u find a way of providing alternative link to starter
project for embu lite as well. The link you gave is also not working. I had
to get if from github and try to find the project that match the tutorial 5
and i started from there. We are having big challage with amaozon web
service actually.

May be in the next version of the book you publicize the alternative link
for dependencies

[image: Makerere University]

Simon Peter Ojok
Student | Makerere University | SCIT
phone: +256754140200
mobile: +256772241709
email: simonojok19@gmail.com
address: Kampala-Uganda
<http://pysimonojok/>
<http://pysimonojok/>
<http://pysimonojok/>
<http://7.176.192.128/>

**Comment by commonsguy** [comment]
> Please i don't know but i have found out that most of people learning
android development and following ur book are have similar problems you
have just fixed with me.

I am going to guess that you are referring to only developers in Uganda.

> May be in the next version of the book you publicize the alternative link
for dependencies

*The Busy Coder's Guide to Android Development* is no longer being updated.

More generally, has the Ugandan developer community published a report outlining what is and is not working? For example:

- Which artifact repositories work? Maven Central? JCenter? Jitpack? Others?

- Which project repositories work? GItHub? GitLab? Bitbucket? Others?

- Which file hosting services work? (apparently not Amazon S3)

- Which VPS providers work? (apparently not Linode)
