### ISSUE TITLE
Support CA Pinning

### ISSUE THREAD

**Issue by commonsguy** [commonsguy/cwac-security#3]
[Moxie Marlinspike's implementation](https://github.com/moxie0/AndroidPinning/blob/master/java/org/thoughtcrime/ssl/pinning/PinningTrustManager.java) supports N pins (we only need one pin, rest achieved through `or()`) and is GPLv3 licensed.

Also consider a Java version of the pin creation tool, since Windows users are unlikely to have Python installed.

**Comment by scottyab** [comment]
I created a java based SSL pin creator that's compatible with OKhttp 2.1+ pinning support. https://github.com/scottyab/ssl-pin-generator

**Comment by commonsguy** [comment]
@scottyab Very cool! I'll play with this and will link to it from this repo's documentation once I get it working. Many thanks!

**Comment by commonsguy** [comment]
Also see https://www.cigital.com/blog/ineffective-certificate-pinning-implementations/

**Comment by commonsguy** [comment]
Closing as now being off-topic. I have migrated all my networking stuff to [cwac-netsecurity](https://github.com/commonsguy/cwac-netsecurity), focusing mostly on a backport of the Android 7.0 network security configuration code.
