### ISSUE TITLE
Work together on a unified SSL library

### ISSUE THREAD

**Issue by ge0rg** [commonsguy/cwac-security#7]
While this might not be the ideal medium to communicate this, I think it would be a good idea to unify our work on providing a superior SSL/TLS library for handling different situations.

Currently, we have:

 * moxie's [AndroidPinning](https://github.com/moxie0/AndroidPinning)
 * my [MTM](https://github.com/ge0rg/MemorizingTrustManager/wiki)
 * fdroid's adaptation of MTM for some custom use cases
 * a great proposal by the GuardianProject: [Chained TLS Cert Verification](https://dev.guardianproject.info/projects/bazaar/wiki/Chained_TLS_Cert_Verification)

It would be great if we could unify our resources to provide one easy to use library for the most common use cases (private server, private CA, private cloud), while implementing the Chained approach as far as possible.

**Comment by commonsguy** [comment]
Closing as now being off-topic. I have migrated all my networking stuff to [cwac-netsecurity](https://github.com/commonsguy/cwac-netsecurity), focusing mostly on a backport of the Android 7.0 network security configuration code.
